version: '3.2'
services:
  node:
    ports:
      - target: 26657
        published: "26657"
        mode: host
    command: start -genesis-remote 0.0.0.0:26657 -root-dir .
    build:
      context: .
      target: gnoland-slim
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 10s
    healthcheck:
      test: curl -X POST -f http://0.0.0.0:26657/status || exit 1
      interval: 5s
      timeout: 5s
      start_period: 30s
      start_interval: 1s
  archiver-backup:
    image: ghcr.io/gnolang/tx-archive:latest
    command: backup -remote https://test3.gno.land:36657 -watch -output-path /data/backup.jsonl -overwrite
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          window: 10s
    volumes:
      - ./archiver-data:/data
  archiver-restorer:
    depends_on: 
      node:
        condition: service_healthy
      archiver-backup:
        condition: service_started
    image: ghcr.io/gnolang/tx-archive:latest
    command: restore -remote http://node:26657 -watch -input-path /data/backup.jsonl
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          window: 10s
    volumes:
      - ./archiver-data:/data
