name: gobenchdata publish
on: push
  # branches: [ "master" ]
jobs:
  publish:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: { go-version: "1.20" }
    - name: gobenchdata publish
      run: go run go.bobheadxi.dev/gobenchdata@v1 action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_PRUNE_COUNT: 0
        INPUT_GO_TEST_FLAGS: -cpu 1,2 -run=^$
        INPUT_PUBLISH: true
        INPUT_PUBLISH_BRANCH: gh-pages
