name: benchmarks publish
on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: { go-version: "1.20" }
    - name: gobenchdata publish
      run: go run go.bobheadxi.dev/gobenchdata@v1 action
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INPUT_PRUNE_COUNT: 30
        INPUT_GO_TEST_FLAGS: -short -run=^$ # TODO: remove -short flag
        INPUT_PUBLISH: true
        INPUT_PUBLISH_REPO: github.com/gnolang/benchmarks
        INPUT_PUBLISH_BRANCH: gh-pages
        INPUT_BENCHMARKS_OUT: .benchmarks/benchmarks.json
        INPUT_GIT_COMMIT_MESSAGE: "add new benchmark run from benchmarks publish job"