name: run benchmarks
on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
      test-flags:
        required: true
        type: string
jobs:
  benchmarks:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: 
        go-version: "1.20"
    - name: "gobenchdata publish: ${{ inputs.publish }}"
      run: go run go.bobheadxi.dev/gobenchdata@v1 action
      env:
        GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}
        INPUT_PRUNE_COUNT: 30
        INPUT_GO_TEST_FLAGS: ${{ inputs.test-flags }}
        INPUT_PUBLISH: ${{ inputs.publish }}
        INPUT_PUBLISH_REPO: ajnavarro/gno-benchmarks #TODO: change to gnolang when ready
        INPUT_PUBLISH_BRANCH: gh-pages
        INPUT_BENCHMARKS_OUT: benchmarks.json
        INPUT_GIT_COMMIT_MESSAGE: "add new benchmark run"
        INPUT_CHECKS: ${{ !inputs.publish }}
        INPUT_CHECKS_CONFIG: .benchmarks/gobenchdata-checks.yml