name: run benchmarks on every PR

on:
  pull_request:
jobs:
  publish:
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      publish: true
      test-flags: "-short -run=^$"