name: gno.land

on:
  pull_request:
    paths:
      - "go.sum"
      - "gnovm/**.go"
      - "gnovm/**.gno"
      - "tm2/**.go"
      - "gno.land/**"
      - ".github/workflows/gnovm.yml"
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.20.x"
          - "1.21.x"
        goarch: [ "amd64" ]
        goos: [ "linux" ]
        program:
          - gnoland
          - gnokey
          - gnoweb
          - gnofaucet
          - gnotxsync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: go install
        working-directory: gno.land
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go install ./cmd/${{ matrix.program }}

  test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.20.x"
          - "1.21.x"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: test
        working-directory: gno.land
        run: |
          export GOPATH=$HOME/go
          export GOTEST_FLAGS="-v -p 1 -timeout=30m -coverprofile=coverage.out -covermode=atomic"
          make test
      - if: runner.os == 'Linux'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: gno.land
          files: ./gno.land/coverage.out
          fail_ci_if_error: ${{ github.repository == 'gnolang/gno' }}


  docker-integration:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      # TODO: setup docker caching
      - run: make test.docker
      - run: docker logs int_gnoland || true

  # TODO: docker-less integration test?
